name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Docker 로그인
            echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            # deploy-configs 디렉토리로 이동 및 최신화
            cd ~/DEPLOY-CONFIGS/
            git pull origin main

            # S3에서 .env 파일 가져오기
            aws s3 cp s3://${{ secrets.PRIVATE_S3_BUCKET_NAME }}/deploy/.env ./.env

            # spring-app 중지 및 삭제
            docker compose stop spring-app || true
            docker compose rm -f spring-app || true

            # 이전 Docker 이미지 정리
            docker images ${{ secrets.DOCKER_USERNAME }}/channeling-be -q | xargs -r docker rmi -f || true
            docker image prune -f

            # Docker 이미지 Pull
            docker pull ${{ secrets.DOCKER_USERNAME }}/channeling-be:latest

            # logs 디렉토리 생성 및 권한 설정
            sudo mkdir -p logs
            sudo chown 1000:1000 logs

            # spring-app 컨테이너 실행
            docker compose up -d --no-deps spring-app
